// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using desafio_girafales.Infraestrutura;

#nullable disable

namespace desafio_girafales.Migrations
{
    [DbContext(typeof(DbContexto))]
    partial class DbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bloco A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bloco B"
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CS101-1",
                            Semester = 1,
                            SubjectId = 1,
                            Year = 2025
                        },
                        new
                        {
                            Id = 2,
                            Code = "CS201-1",
                            Semester = 2,
                            SubjectId = 2,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RoomId");

                    b.ToTable("ClassSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            RoomId = 1,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            RoomId = 2,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ciência da Computação"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Matemática"
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TitleId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            TitleId = 3
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            TitleId = 1
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 2
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 0,
                            Name = "",
                            SubjectId = "CS101"
                        },
                        new
                        {
                            Id = 2,
                            Code = 0,
                            Name = "",
                            SubjectId = "CS201"
                        },
                        new
                        {
                            Id = 3,
                            Code = 0,
                            Name = "",
                            SubjectId = "MAT101"
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.SubjectPrerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectPrerequisites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrerequisiteId = 1,
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Professor Assistente"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Professor Associado"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Professor Titular"
                        });
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Class", b =>
                {
                    b.HasOne("desafio_girafales.Dominio.Entidades.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.ClassSchedule", b =>
                {
                    b.HasOne("desafio_girafales.Dominio.Entidades.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("desafio_girafales.Dominio.Entidades.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Professor", b =>
                {
                    b.HasOne("desafio_girafales.Dominio.Entidades.Department", "Department")
                        .WithMany("Professors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("desafio_girafales.Dominio.Entidades.Title", "Title")
                        .WithMany("Professors")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Room", b =>
                {
                    b.HasOne("desafio_girafales.Dominio.Entidades.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.SubjectPrerequisite", b =>
                {
                    b.HasOne("desafio_girafales.Dominio.Entidades.Subject", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("desafio_girafales.Dominio.Entidades.Subject", "Subject")
                        .WithMany("Prerequisites")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prerequisite");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Department", b =>
                {
                    b.Navigation("Professors");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Subject", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("desafio_girafales.Dominio.Entidades.Title", b =>
                {
                    b.Navigation("Professors");
                });
#pragma warning restore 612, 618
        }
    }
}
